### PR TITLE
"Fix" all typescript errors

### LINKED ISSUE #15: Fix all Typescript errors, disallow new ones
Frontend is currently holding strong at ~100 errors. Much of them are very simple (implicit any etc.) and some are blocked by #14. We should fix all of them, and then implement a pre-push hook that prevents pushing new ones.

### PR DESCRIPTION
**Pull request by wbobeirne**
Closes #15

### What This Does

* Fixes all of the "easy" typescript errors
* Makes all `any`s explicit
* Adds a pre-push hook that lints and tsc's before allowing a push. Can be overridden with `--no-verify`

### What This Doesn't Do

* Add continuous integration
* Integrate TypeChain types
* Type all web3 interactions
* Convert all numbers to BigNumber
* [Show typescript errors in webpack console](https://github.com/zeit/next-plugins/tree/master/packages/next-typescript#type-checking) (Should we add this? Might not be needed if we switch off of Next.)

### CODE REVIEW

File: frontend/client/lib/getWeb3.ts [hunk 1]
```diff
@@ -1,7 +1,15 @@
 import Web3 from 'web3';
 
-const resolveWeb3 = (resolve, reject) => {
-  let { web3 } = window;
+interface Web3Window extends Window {
+  web3?: Web3;
+}
+
+const resolveWeb3 = (resolve: (web3: Web3) => void, reject: (err: Error) => void) => {
+  if (typeof window === 'undefined') {
```
Comment (dternyak) [inline frontend/client/lib/getWeb3.ts]: 👍
